return {
	"MeanderingProgrammer/render-markdown.nvim",
	enabled = true,
	dependencies = {
		"nvim-treesitter/nvim-treesitter",
		"nvim-tree/nvim-web-devicons",
		"echasnovski/mini.nvim",
	},
  after = {'nvim-treesitter'},
	---@module 'render-markdown'
	---@type render.md.UserConfig
	opts = {
		-- NOTE: Heading
		heading = {
			enabled = true,
			render_modes = false,
			atx = true,
			setext = true,
			sign = true,
			icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
			position = "overlay",
			signs = { "󰫎 " },
			width = "full",
			left_margin = 0,
			left_pad = 0,
			right_pad = 0,
			min_width = 0,
			border = false,
			border_virtual = false,
			border_prefix = false,
			above = "▄",
			below = "▀",
			backgrounds = {
				"RenderMarkdownH1Bg",
				"RenderMarkdownH2Bg",
				"RenderMarkdownH3Bg",
				"RenderMarkdownH4Bg",
				"RenderMarkdownH5Bg",
				"RenderMarkdownH6Bg",
			},
			foregrounds = {
				"RenderMarkdownH1",
				"RenderMarkdownH2",
				"RenderMarkdownH3",
				"RenderMarkdownH4",
				"RenderMarkdownH5",
				"RenderMarkdownH6",
			},
			custom = {},
		},

		code = {
			enabled = true,
			render_modes = false,
			sign = true,
			conceal_delimiters = true,
			language = true,
			position = "left",
			language_icon = true,
			language_name = true,
			language_info = true,
			language_pad = 0,
			disable_background = { "diff" },
			width = "block",
			left_margin = 0,
			left_pad = 2,
			right_pad = 0,
			min_width = 45,
			border = "hide",
			language_border = " ",
			language_left = "",
			language_right = "",
			above = "▄",
			below = "▀",
			inline = true,
			inline_left = "",
			inline_right = "",
			inline_pad = 0,
			highlight = "RenderMarkdownCode",
			highlight_info = "RenderMarkdownCodeInfo",
			highlight_language = nil,
			highlight_border = "RenderMarkdownCodeBorder",
			highlight_fallback = "RenderMarkdownCodeFallback",
			highlight_inline = "RenderMarkdownCodeInline",
			style = "full",
		},
	},
}
